---
title: "Create UrbanSim Control Totals"
format: html
editor: source
project: execute-dir: project
---

# 1 - Set Scenario Name, knitr path, and root directory, load packages

```{r, setup, include=FALSE}

pacman::p_load(
  tidyverse,
  tidycensus,
  mapcdatakeys,
  janitor,
  readxl,
  rjson,
  stringr,
  data.table,
  here
)
# Set Scenario name

# scen <- 'Scenario_1'
# scen <- 'Scenario_2'
scen <- 'Scenario_3'
# scen <- 'Scenario_4'

# Set ACS / PUMS vintage
vintage <-  2021

# List of RPA names
mpos <- unlist(c(mapcdatakeys::all_muni_data_keys |> select(mpo) |> unique()))

# Paths
if (grepl('VM',Sys.info()[['nodename']])){
  base <- '//data-sync/Public/DataServices'
} else {
  base <- 'S:/Network Shares/K Drive/DataServices'
}

# Root Directory
root <- paste0(base,'/Projects/Current_Projects/Projections/Projections_2028/Data/01_Regional_Control_Totals/')

shop_path <- paste0(base,'/Projects/Current_Projects/Housing/StatewideHousingPlan/04_Analysis/Data/Working/Reweighter/',scen,'/Output_Files_UPDATE/')

input_path <- paste0(root, 'SHoP_Scenarios/Reweighter_Outputs/',scen,'/')

output_path <- paste0(root, 'SHoP_Scenarios/UrbanSim_Inputs/',scen,'/')

dir.create(output_path, showWarnings = F)

# CPI deflator
# Load CPI time series for deflating income variable
cpi <- fread(paste0(root,'cpi_deflators_by_year.csv'))
cpi.deflator <- cpi[year==2013, index] / cpi[year==vintage, index]


#MAPC/UrbanSim Subregion Crosswalk File.
subregion_xwalk <- fread(paste0(root,'subregions_crosswalk.csv'))

#Set knitr path
knitr::opts_knit$set(root.dir = input_path)

## turn off scientific notation
options(scipen = 999)
#Set random seed
set.seed(351)
# Helper function
sun <- function(x){sort(unique(x))}
lun <- function(x){length(unique(x))}

```

# 2 - Load and Process Reweighter Outputs

## 2a - SWM with population post-processing

```{r}


swm.ctrl.pp <- data.table()

# Statewide model
reb <- 'MAPC97'

for (yr in 2020) {
  if (!file.exists(paste0(
    input_path,
    'processor_corrected_PUMS_',
    reb,
    '_',
    scen,
    '_',
    yr,
    '.rds'
  ))) {
    file.copy(
      paste0(
        shop_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_',
        yr,
        '.rds'
      ),
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_',
        yr,
        '.rds'
      )
    )
  }
  
  dt <- readRDS(paste0(
    input_path,
    'processor_corrected_PUMS_',
    reb,
    '_',
    scen,
    '_',
    yr,
    '.rds'
  )) |>
    group_by(hid) |>
    mutate(HINCP = sum(PINCP)) |>
    ungroup() |>
    mutate(
      child_flag = case_when(Child_Total == 0 | NP == 1 ~ 0, Child_Total > 0 &
                               NP > 1 ~ 1),
      NP = HHsize
    ) |>
    filter(SPORDER == 1) |>
    left_join(subregion_xwalk, by = c('mpo' = 'RPA')) |>
    rename(subregion_code = subregion_code_urbansim) |>
    mutate(
      HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
      US_AGEHHDER = case_when(
        AGEP < 15 ~ 0,
        AGEP >= 15 & AGEP <= 35 ~ 1,
        AGEP >= 36 & AGEP <= 45 ~ 2,
        AGEP >= 46 & AGEP <= 65 ~ 3,
        AGEP >= 66 & AGEP <= 75 ~ 4,
        AGEP >= 76 ~ 5
      ),
      US_HINC = case_when(
        HINCP.2013 <= 35000 ~ "1",
        HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
        HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
        HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
        HINCP.2013 > 225000 ~ "5"
      ),
      HHSize = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
      age_of_head_min = case_when(
        US_AGEHHDER == 1 ~ 15,
        US_AGEHHDER == 2 ~ 35,
        US_AGEHHDER == 3 ~ 45,
        US_AGEHHDER == 4 ~ 65,
        US_AGEHHDER == 5 ~ 75
      ),
      age_of_head_max = case_when(
        US_AGEHHDER == 1 ~ 35,
        US_AGEHHDER == 2 ~ 45,
        US_AGEHHDER == 3 ~ 65,
        US_AGEHHDER == 4 ~ 75,
        US_AGEHHDER == 5 ~ -1
      ),
      income_min = case_when(
        US_HINC == 1 ~ 0,
        US_HINC == 2 ~ 35000,
        US_HINC == 3 ~ 75000,
        US_HINC == 4 ~ 125000,
        US_HINC == 5 ~ 225000
      ),
      income_max = case_when(
        US_HINC == 1 ~ 35000,
        US_HINC == 2 ~ 75000,
        US_HINC == 3 ~ 125000,
        US_HINC == 4 ~ 225000,
        US_HINC == 5 ~ -1
      ),
      persons_min = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ 4),
      persons_max = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ -1),
      children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
      children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
    ) |>
    group_by(
      year,
      subregion_code,
      age_of_head_min,
      age_of_head_max,
      income_min,
      income_max,
      persons_min,
      persons_max,
      children_min,
      children_max
    ) |>
    summarize(total_number_of_households = round(sum(new_WGTP))) |>
    ungroup() |>
    relocate(total_number_of_households, .before = age_of_head_min) |>
    setDT()
  
  swm.ctrl.pp <- rbind(swm.ctrl.pp, dt)
  rm(dt)
  gc()
  message(paste0('SWM Control Totals ', yr, ' Complete'))
}

if (scen %in% c('Scenario_2', 'Scenario_3')) {
  for (yr in c(2030, 2035, 2040, 2045, 2050)) {
    if (!file.exists(
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_with_ShelterPop_',
        yr,
        '.rds'
      )
    )) {
      file.copy(
        paste0(
          shop_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_with_ShelterPop_',
          yr,
          '.rds'
        ),
        paste0(
          input_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_with_ShelterPop_',
          yr,
          '.rds'
        )
      )
    }
    dt <- readRDS(
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_with_ShelterPop_',
        yr,
        '.rds'
      )
    )
    dt[SHELT==0, HINCP:=sum(PINCP), hid]
    dt[is.na(NP) & !is.na(household.size), NP:=household.size]
    dt[Child_Total==0 | NP==1,child_flag:=0]
    dt[Child_Total>0 & NP>1,child_flag:=1]
    dt[,year:=yr]
    
    dt <- dt |>
      filter(SPORDER == 1) |>
      left_join(subregion_xwalk, by = c('mpo' = 'RPA')) |>
      rename(subregion_code = subregion_code_urbansim) |>
      mutate(
        HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
        US_AGEHHDER = case_when(
          AGEP < 15 ~ 0,
          AGEP >= 15 & AGEP <= 35 ~ 1,
          AGEP >= 36 & AGEP <= 45 ~ 2,
          AGEP >= 46 & AGEP <= 65 ~ 3,
          AGEP >= 66 & AGEP <= 75 ~ 4,
          AGEP >= 76 ~ 5
        ),
        US_HINC = case_when(
          HINCP.2013 <= 35000 ~ "1",
          HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
          HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
          HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
          HINCP.2013 > 225000 ~ "5"
        ),
        HHSize4 = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
        age_of_head_min = case_when(
          US_AGEHHDER == 1 ~ 15,
          US_AGEHHDER == 2 ~ 35,
          US_AGEHHDER == 3 ~ 45,
          US_AGEHHDER == 4 ~ 65,
          US_AGEHHDER == 5 ~ 75
        ),
        age_of_head_max = case_when(
          US_AGEHHDER == 1 ~ 35,
          US_AGEHHDER == 2 ~ 45,
          US_AGEHHDER == 3 ~ 65,
          US_AGEHHDER == 4 ~ 75,
          US_AGEHHDER == 5 ~ -1
        ),
        income_min = case_when(
          US_HINC == 1 ~ 0,
          US_HINC == 2 ~ 35000,
          US_HINC == 3 ~ 75000,
          US_HINC == 4 ~ 125000,
          US_HINC == 5 ~ 225000
        ),
        income_max = case_when(
          US_HINC == 1 ~ 35000,
          US_HINC == 2 ~ 75000,
          US_HINC == 3 ~ 125000,
          US_HINC == 4 ~ 225000,
          US_HINC == 5 ~ -1
        ),
        persons_min = case_when(HHSize4 == 1 ~ 1, HHSize4 == 2 ~ 2, HHSize4 == 3 ~ 3, HHSize4 == 4 ~ 4),
        persons_max = case_when(HHSize4 == 1 ~ 1, HHSize4 == 2 ~ 2, HHSize4 == 3 ~ 3, HHSize4 == 4 ~ -1),
        children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
        children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
      ) |>
      group_by(
        year,
        subregion_code,
        age_of_head_min,
        age_of_head_max,
        income_min,
        income_max,
        persons_min,
        persons_max,
        children_min,
        children_max
      ) |>
      summarize(total_number_of_households = round(sum(new_WGTP))) |>
      ungroup() |>
      relocate(total_number_of_households, .before = age_of_head_min) |>
      setDT()
    
    swm.ctrl.pp <- rbind(swm.ctrl.pp, dt)
    rm(dt)
    gc()
    message(paste0('SWM Control Totals ', yr, ' Complete'))
    
  }
} else {
  for (yr in c(2030, 2035, 2040, 2045, 2050)) {
    if (!file.exists(paste0(
      input_path,
      'processor_corrected_PUMS_',
      reb,
      '_',
      scen,
      '_',
      yr,
      '.rds'
    ))) {
      file.copy(
        paste0(
          shop_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_',
          yr,
          '.rds'
        ),
        paste0(
          input_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_',
          yr,
          '.rds'
        )
      )
    }
    dt <- readRDS(paste0(
      input_path,
      'processor_corrected_PUMS_',
      reb,
      '_',
      scen,
      '_',
      yr,
      '.rds'
    )) |>
      group_by(hid) |>
    mutate(HINCP = sum(PINCP)) |>
    ungroup() |>
    mutate(
      child_flag = case_when(Child_Total == 0 | NP == 1 ~ 0, Child_Total > 0 &
                               NP > 1 ~ 1),
      NP = HHsize
    ) |>
    filter(SPORDER == 1) |>
    left_join(subregion_xwalk, by = c('mpo' = 'RPA')) |>
    rename(subregion_code = subregion_code_urbansim) |>
    mutate(
      HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
      US_AGEHHDER = case_when(
        AGEP < 15 ~ 0,
        AGEP >= 15 & AGEP <= 35 ~ 1,
        AGEP >= 36 & AGEP <= 45 ~ 2,
        AGEP >= 46 & AGEP <= 65 ~ 3,
        AGEP >= 66 & AGEP <= 75 ~ 4,
        AGEP >= 76 ~ 5
      ),
      US_HINC = case_when(
        HINCP.2013 <= 35000 ~ "1",
        HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
        HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
        HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
        HINCP.2013 > 225000 ~ "5"
      ),
      HHSize = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
      age_of_head_min = case_when(
        US_AGEHHDER == 1 ~ 15,
        US_AGEHHDER == 2 ~ 35,
        US_AGEHHDER == 3 ~ 45,
        US_AGEHHDER == 4 ~ 65,
        US_AGEHHDER == 5 ~ 75
      ),
      age_of_head_max = case_when(
        US_AGEHHDER == 1 ~ 35,
        US_AGEHHDER == 2 ~ 45,
        US_AGEHHDER == 3 ~ 65,
        US_AGEHHDER == 4 ~ 75,
        US_AGEHHDER == 5 ~ -1
      ),
      income_min = case_when(
        US_HINC == 1 ~ 0,
        US_HINC == 2 ~ 35000,
        US_HINC == 3 ~ 75000,
        US_HINC == 4 ~ 125000,
        US_HINC == 5 ~ 225000
      ),
      income_max = case_when(
        US_HINC == 1 ~ 35000,
        US_HINC == 2 ~ 75000,
        US_HINC == 3 ~ 125000,
        US_HINC == 4 ~ 225000,
        US_HINC == 5 ~ -1
      ),
      persons_min = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ 4),
      persons_max = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ -1),
      children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
      children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
    ) |>
    group_by(
      year,
      subregion_code,
      age_of_head_min,
      age_of_head_max,
      income_min,
      income_max,
      persons_min,
      persons_max,
      children_min,
      children_max
    ) |>
    summarize(total_number_of_households = round(sum(new_WGTP))) |>
    ungroup() |>
    relocate(total_number_of_households, .before = age_of_head_min) |>
    setDT()
    
    swm.ctrl.pp <- rbind(swm.ctrl.pp, dt)
    rm(dt)
    gc()
    message(paste0('SWM Control Totals ', yr, ' Complete'))
    
  }
}

saveRDS(
  swm.ctrl.pp,
  paste0(
    output_path,
    'swm_control_totals_',
    reb,
    '_pop_corrected_raw_5_year.rds'
  )
)

```

## 2b - MAPC with population post-processing

```{r}


mapc.ctrl.pp <- data.table()
reb <- 'MAPC101'
yrs <- c(2020, 2025)

for (yr in yrs) {
  if (!file.exists(paste0(
    input_path,
    'processor_corrected_PUMS_',
    reb,
    '_',
    scen,
    '_',
    yr,
    '.rds'
  ))) {
    file.copy(
      paste0(
        shop_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_',
        yr,
        '.rds'
      ),
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_',
        yr,
        '.rds'
      )
    )
  }
  
  dt <- readRDS(paste0(
    input_path,
    'processor_corrected_PUMS_',
    reb,
    '_',
    scen,
    '_',
    yr,
    '.rds'
  )) |>
    group_by(hid) |>
    mutate(HINCP = sum(PINCP)) |>
    ungroup() |>
    mutate(
      child_flag = case_when(Child_Total == 0 | NP == 1 ~ 0, Child_Total > 0 &
                               NP > 1 ~ 1),
      NP = HHsize
    ) |>
    filter(SPORDER == 1) |>
    mutate(
      HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
      US_AGEHHDER = case_when(
        AGEP < 15 ~ 0,
        AGEP >= 15 & AGEP <= 35 ~ 1,
        AGEP >= 36 & AGEP <= 45 ~ 2,
        AGEP >= 46 & AGEP <= 65 ~ 3,
        AGEP >= 66 & AGEP <= 75 ~ 4,
        AGEP >= 76 ~ 5
      ),
      US_HINC = case_when(
        HINCP.2013 <= 35000 ~ "1",
        HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
        HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
        HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
        HINCP.2013 > 225000 ~ "5"
      ),
      HHSize = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
      age_of_head_min = case_when(
        US_AGEHHDER == 1 ~ 15,
        US_AGEHHDER == 2 ~ 35,
        US_AGEHHDER == 3 ~ 45,
        US_AGEHHDER == 4 ~ 65,
        US_AGEHHDER == 5 ~ 75
      ),
      age_of_head_max = case_when(
        US_AGEHHDER == 1 ~ 35,
        US_AGEHHDER == 2 ~ 45,
        US_AGEHHDER == 3 ~ 65,
        US_AGEHHDER == 4 ~ 75,
        US_AGEHHDER == 5 ~ -1
      ),
      income_min = case_when(
        US_HINC == 1 ~ 0,
        US_HINC == 2 ~ 35000,
        US_HINC == 3 ~ 75000,
        US_HINC == 4 ~ 125000,
        US_HINC == 5 ~ 225000
      ),
      income_max = case_when(
        US_HINC == 1 ~ 35000,
        US_HINC == 2 ~ 75000,
        US_HINC == 3 ~ 125000,
        US_HINC == 4 ~ 225000,
        US_HINC == 5 ~ -1
      ),
      persons_min = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ 4),
      persons_max = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ -1),
      children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
      children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
    ) |>
    group_by(
      year,
      age_of_head_min,
      age_of_head_max,
      income_min,
      income_max,
      persons_min,
      persons_max,
      children_min,
      children_max
    ) |>
    summarize(total_number_of_households = round(sum(new_WGTP))) |>
    ungroup() |>
    relocate(total_number_of_households, .before = age_of_head_min) |>
    setDT()
  
  mapc.ctrl.pp <- rbind(mapc.ctrl.pp, dt)
  rm(dt)
  gc()
  message(paste0('MAPCM Control Totals ', yr, ' Complete'))
}


if (scen %in% c('Scenario_2', 'Scenario_3')) {
  for (yr in c(2030, 2035, 2040, 2045, 2050)) {
  if (!file.exists(
    paste0(
      input_path,
      'processor_corrected_PUMS_',
      reb,
      '_',
      scen,
      '_with_ShelterPop_',
      yr,
      '.rds'
    )
  )) {
    file.copy(
      paste0(
        shop_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_with_ShelterPop_',
        yr,
        '.rds'
      ),
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_with_ShelterPop_',
        yr,
        '.rds'
      )
    )
  }
  
    dt <- readRDS(
      paste0(
        input_path,
        'processor_corrected_PUMS_',
        reb,
        '_',
        scen,
        '_with_ShelterPop_',
        yr,
        '.rds'
      )
    )
    dt[SHELT==0, HINCP:=sum(PINCP), hid]
    dt[is.na(NP) & !is.na(household.size), NP:=household.size]
    dt[Child_Total==0 | NP==1,child_flag:=0]
    dt[Child_Total>0 & NP>1,child_flag:=1]
    dt[,year:=yr]
    
    dt <- dt |>
      filter(SPORDER == 1) |>
      mutate(
        HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
        US_AGEHHDER = case_when(
          AGEP < 15 ~ 0,
          AGEP >= 15 & AGEP <= 35 ~ 1,
          AGEP >= 36 & AGEP <= 45 ~ 2,
          AGEP >= 46 & AGEP <= 65 ~ 3,
          AGEP >= 66 & AGEP <= 75 ~ 4,
          AGEP >= 76 ~ 5
        ),
        US_HINC = case_when(
          HINCP.2013 <= 35000 ~ "1",
          HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
          HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
          HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
          HINCP.2013 > 225000 ~ "5"
        ),
        HHSize4 = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
        age_of_head_min = case_when(
          US_AGEHHDER == 1 ~ 15,
          US_AGEHHDER == 2 ~ 35,
          US_AGEHHDER == 3 ~ 45,
          US_AGEHHDER == 4 ~ 65,
          US_AGEHHDER == 5 ~ 75
        ),
        age_of_head_max = case_when(
          US_AGEHHDER == 1 ~ 35,
          US_AGEHHDER == 2 ~ 45,
          US_AGEHHDER == 3 ~ 65,
          US_AGEHHDER == 4 ~ 75,
          US_AGEHHDER == 5 ~ -1
        ),
        income_min = case_when(
          US_HINC == 1 ~ 0,
          US_HINC == 2 ~ 35000,
          US_HINC == 3 ~ 75000,
          US_HINC == 4 ~ 125000,
          US_HINC == 5 ~ 225000
        ),
        income_max = case_when(
          US_HINC == 1 ~ 35000,
          US_HINC == 2 ~ 75000,
          US_HINC == 3 ~ 125000,
          US_HINC == 4 ~ 225000,
          US_HINC == 5 ~ -1
        ),
        persons_min = case_when(HHSize4 == 1 ~ 1, HHSize4 == 2 ~ 2, HHSize4 == 3 ~ 3, HHSize4 == 4 ~ 4),
        persons_max = case_when(HHSize4 == 1 ~ 1, HHSize4 == 2 ~ 2, HHSize4 == 3 ~ 3, HHSize4 == 4 ~ -1),
        children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
        children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
      ) |>
      group_by(
        year,
        age_of_head_min,
        age_of_head_max,
        income_min,
        income_max,
        persons_min,
        persons_max,
        children_min,
        children_max
      ) |>
      summarize(total_number_of_households = round(sum(new_WGTP))) |>
      ungroup() |>
      relocate(total_number_of_households, .before = age_of_head_min) |>
      setDT()
    
    mapc.ctrl.pp <- rbind(mapc.ctrl.pp, dt)
    rm(dt)
    gc()
    message(paste0('MAPCM Control Totals ', yr, ' Complete'))
    
  }
} else {
  for (yr in c(2030, 2035, 2040, 2045, 2050)) {
    if (!file.exists(paste0(
      input_path,
      'processor_corrected_PUMS_',
      reb,
      '_',
      scen,
      '_',
      yr,
      '.rds'
    ))) {
      file.copy(
        paste0(
          shop_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_',
          yr,
          '.rds'
        ),
        paste0(
          input_path,
          'processor_corrected_PUMS_',
          reb,
          '_',
          scen,
          '_',
          yr,
          '.rds'
        )
      )
    }
    dt <- readRDS(paste0(
      input_path,
      'processor_corrected_PUMS_',
      reb,
      '_',
      scen,
      '_',
      yr,
      '.rds'
    )) |>
      group_by(hid) |>
    mutate(HINCP = sum(PINCP)) |>
    ungroup() |>
    mutate(
      child_flag = case_when(Child_Total == 0 | NP == 1 ~ 0, Child_Total > 0 &
                               NP > 1 ~ 1),
      NP = HHsize
    ) |>
    filter(SPORDER == 1) |>
    mutate(
      HINCP.2013 = round(HINCP * ADJINC * cpi.deflator, 0),
      US_AGEHHDER = case_when(
        AGEP < 15 ~ 0,
        AGEP >= 15 & AGEP <= 35 ~ 1,
        AGEP >= 36 & AGEP <= 45 ~ 2,
        AGEP >= 46 & AGEP <= 65 ~ 3,
        AGEP >= 66 & AGEP <= 75 ~ 4,
        AGEP >= 76 ~ 5
      ),
      US_HINC = case_when(
        HINCP.2013 <= 35000 ~ "1",
        HINCP.2013 > 35000 & HINCP.2013 <= 75000 ~ "2",
        HINCP.2013 > 75000 & HINCP.2013 <= 125000 ~ "3",
        HINCP.2013 > 125000 & HINCP.2013 <= 225000 ~ "4",
        HINCP.2013 > 225000 ~ "5"
      ),
      HHSize = case_when(NP == 1 ~ 1, NP == 2 ~ 2, NP == 3 ~ 3, NP >= 4 ~ 4),
      age_of_head_min = case_when(
        US_AGEHHDER == 1 ~ 15,
        US_AGEHHDER == 2 ~ 35,
        US_AGEHHDER == 3 ~ 45,
        US_AGEHHDER == 4 ~ 65,
        US_AGEHHDER == 5 ~ 75
      ),
      age_of_head_max = case_when(
        US_AGEHHDER == 1 ~ 35,
        US_AGEHHDER == 2 ~ 45,
        US_AGEHHDER == 3 ~ 65,
        US_AGEHHDER == 4 ~ 75,
        US_AGEHHDER == 5 ~ -1
      ),
      income_min = case_when(
        US_HINC == 1 ~ 0,
        US_HINC == 2 ~ 35000,
        US_HINC == 3 ~ 75000,
        US_HINC == 4 ~ 125000,
        US_HINC == 5 ~ 225000
      ),
      income_max = case_when(
        US_HINC == 1 ~ 35000,
        US_HINC == 2 ~ 75000,
        US_HINC == 3 ~ 125000,
        US_HINC == 4 ~ 225000,
        US_HINC == 5 ~ -1
      ),
      persons_min = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ 4),
      persons_max = case_when(HHSize == 1 ~ 1, HHSize == 2 ~ 2, HHSize == 3 ~ 3, HHSize == 4 ~ -1),
      children_min = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ 1),
      children_max = case_when(child_flag == 0 ~ 0, child_flag == 1 ~ -1)
    ) |>
    group_by(
      year,
      age_of_head_min,
      age_of_head_max,
      income_min,
      income_max,
      persons_min,
      persons_max,
      children_min,
      children_max
    ) |>
    summarize(total_number_of_households = round(sum(new_WGTP))) |>
    ungroup() |>
    relocate(total_number_of_households, .before = age_of_head_min) |>
    setDT()
    
    mapc.ctrl.pp <- rbind(mapc.ctrl.pp, dt)
    rm(dt)
    gc()
    message(paste0('MAPCM Control Totals ', yr, ' Complete'))
    
  }
}

saveRDS(
  mapc.ctrl.pp,
  paste0(
    output_path,
    'mapcm_control_totals_',
    reb,
    '_pop_corrected_raw_5_year.rds'
  )
)


```

#3 - Interpolate to annual control totals

## 3a - SWM - with pop correction
```{r}

reb <- 'MAPC97'
swm.10 <- fread(paste0(root,'LRTP_2023/Statewide_Control_HHds_Projections2050_MB_v04.20.23_one_year_offset_HH_Adj.csv')) |> filter(year<2020)

swm.expand.pp <- swm.ctrl.pp %>%
  select(
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max,
    year,
    subregion_code
  ) |>
  group_by(
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max,
    subregion_code
  ) |>
  tidyr::complete(year = tidyr::full_seq(2020:2050, 1)) %>%
  ungroup() |>
  left_join(
    swm.ctrl.pp,
    by = c(
      'age_of_head_min',
      'age_of_head_max',
      'income_min',
      'income_max',
      'persons_min',
      'persons_max',
      'children_min',
      'children_max',
      'year',
      'subregion_code'
    )
  ) |> rbind(swm.10)|>
  setorder(
    year,
    subregion_code,
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max
  ) |> 
  group_by(
    subregion_code,
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max
    ) %>%
  mutate(total_number_of_households = round(zoo::na.approx(total_number_of_households, na.rm = FALSE))) %>% 
  ungroup() |> 
  setDT()


swm.expand.pp[is.na(total_number_of_households), total_number_of_households:=0]

fwrite(swm.expand.pp, paste0(output_path,'SWM_Household_Control_Totals_SHoP_',reb,'_',scen,'_pop_corrected.csv'))


```

## 3b - MAPC - with pop correction

```{r}

reb <- 'MAPC101'

mapc.10 <- fread(paste0(root,'LRTP_2023/MAPC_Control_HHds_Projections2050_MB_97to101_v05.10.23_one_year_offset_HH_adj.csv')) |> filter(year<2020)

mapc.expand.pp <- mapc.ctrl.pp %>%
  select(
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max,
    year
  ) |>
  group_by(
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max
  ) |>
  tidyr::complete(year = tidyr::full_seq(2020:2050, 1)) %>%
  ungroup() |>
  left_join(
    mapc.ctrl.pp,
    by = c(
      'age_of_head_min',
      'age_of_head_max',
      'income_min',
      'income_max',
      'persons_min',
      'persons_max',
      'children_min',
      'children_max',
      'year'
    )
  ) |> rbind(mapc.10)|>
  setorder(
    year,
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max
  ) |> 
  group_by(
    age_of_head_min,
    age_of_head_max,
    income_min,
    income_max,
    persons_min,
    persons_max,
    children_min,
    children_max
    ) %>%
  mutate(total_number_of_households = round(zoo::na.approx(total_number_of_households, na.rm = FALSE))) %>% 
  ungroup() |> 
  setDT()


mapc.expand.pp[is.na(total_number_of_households), total_number_of_households:=0]

fwrite(mapc.expand.pp, paste0(output_path,'MAPC_Household_Control_Totals_SHoP_',reb,'_',scen,'_pop_corrected.csv'))

# 
# new <- fread("S:/Network Shares/K Drive/DataServices/Projects/Current_Projects/Projections/Projections_2028/Data/01_Regional_Control_Totals/SHoP_Scenarios/UrbanSim_Inputs/Scenario_3/SWM_Household_Control_Totals_SHoP_MAPC97_Scenario_3_pop_corrected.csv")
# 
# old <- fread("S:/Network Shares/K Drive/DataServices/Projects/Current_Projects/Projections/Projections_2028/Data/01_Regional_Control_Totals/SHoP_Scenarios/UrbanSim_Inputs/Scenario_3/SWM_Household_Control_Totals_SHoP_Scenario_3_pop_corrected.csv")

```