---
title: "Urbansim Model Update Exploratory Analysis"
format: html
editor: visual
---
# 0.0 Environment and Script Set-up
# 0.1 Load Libraries and Functions
```{r}
# {here} library to initiate conditional filepaths
library(here)
# Libraries used in Urbansim/Projections workflow
source(here("urbansim_model_update/projections_libraries.R"))
# Functions created for the Urbansim/Projections workflow
source(here("urbansim_model_update/projections_functions.R"))
```

# 0.2 Set Environment Variables for this Script
```{r}
# Set random seed
set.seed(351)

# Remove scientific notation
options(scipen = 999)

# Set the PUMS API call variables for this analysis. Used in the 
# Variables from the PUMS data to query (data dictionary is here: https://www.census.gov/programs-surveys/acs/microdata/documentation.2023.html#list-tab-1370939201)
pums.vars <- c(
               # General PUMS variables
               'PUMA', #PUMA designation
               'ADJINC', # Inflation adjustment factor for income variables
               'TYPEHUGQ', # Type of household (Household or group quarters)
  
               #Demographic variables
               'AGEP', # Age of person
               "SEX", # Sex
               'NP', # Number of persons in a household
               'TEN', # Tenure
               'RAC1P', # Race
               'HISP', # Recoded detailed Hispanic origin (Ethnicity)
               'R18', #Presence of persons under 18 years in household
               'R60', # Presence of persons over 60 years in household
               'R65', # Presence of persons over 65 years in household
  
               # Income variables
               "FINCP", # Family Income
               "HINCP", # Household Income
               "INTP", # Interest, dividends, and net rental income
               "PINCP", # Total person's income
               "WAGP", # Wages or salary income past 12 months
               "SSIP", # Supplementary Security Income
               "SSP", # Social Security income
               "SEMP", # Self employment income
               "RETP", # Retirement income
               "PAP", # Public assistance income
               "OIP", #All other income
               
               # Overcrowding and Household Composition variables
               'BDSP', # Number of bedrooms
               'RMSP', # Number of rooms
               'CPLT', # Couple Type
               'RELSHIPP', # Relationship to the householder
               'PSF', # Presence of subfamily
               'SFN', # Subfamily number
               'SFR', # Subfamily relationship
               'NR', # Presence of non-relative in household
               'NRC', # Number of related children in a household
               'MULTG', # Multigenerational household flag
               'HHT', # Household/family type
               'HHT2', # Household family type (including cohabiting)
               "PARTNER", # Unmarried partner household
               'NPP', # Grandparent headed household with no parent present
               'NPF', # Number of persons in family
               'HUGCL', # Household with grandparent living with grandchildren
               'NOC', # Number of own children
               'HUPAC', # Presence and age of children
               'HUPAOC', # Presence and age of own children
               'HUPARC' # Presence and age of related children
               
               # Disability variables
                    
            )

# Terminal year in the vintage
pums.vintage = 2023

# Survey from which the data is requested
survey = "acs5"
```
# 1.0 Load Data
# 1.1 Load PUMS Data from {tidycensus}
```{r}
# Load PUMA to RPA Crosswalk
# For this analysis we will group Martha's Vineyard Commission, Nantucket Planning and Economic Development Commission and Cape Cod Commission into one group -- "CCC" -- which will refer to the Cape and Islands.
puma.rpa_xwalk <- read.csv(here(paste("urbansim_model_update/inputs/puma2020_rpa_crosswalk.csv"))) |> 
  mutate(PUMACE20 = as.character(str_pad(PUMACE20, width = 5, side = "left", pad = 0)))

# Check we have 11 RPAs int the crosswalk
# NPEDC and MVC are cannot be separated from CCC since they share PUMA 1301.
print(length(unique(puma.rpa_xwalk$rpa_acr)))

# Load PUMS data
# Vintage: 2019-2023
# Variables: Described above
# Survey: ACS 5-year PUMS
# Geography: Massachusetts
pums <- pums_query(var.list = pums.vars, yr = pums.vintage, srvy = survey) 

```

# 1.2 Clean PUMS Data
```{r}
pums_cleaned <- pums |> 
  # Filter for households
  filter(TYPEHUGQ == "1" & SPORDER == "1") |> 
  # Join RPA acronyms to PUMS dataframe by PUMA
  left_join(puma.rpa_xwalk, by = c("PUMA" = "PUMACE20")) |> 
  # Adjust income variables 
  mutate(
    HINCP_adj = HINCP*as.numeric(ADJINC)
  )


# Check if we've created any NA values unintentionally.
print(sapply(X = pums_cleaned, FUN =  function(x) sum(is.na(x))))
```

# 2.0 Household Type Analysis
```{r}
```

# 3.0 Income Distribution Analysis
# 3.1 Evaluation of Census Income Thresholds
```{r}
# Standard Urbansim Income Thresholds
income.1 <- pums_cleaned |>
  mutate(
    income.1 = case_when(
      HINCP_adj <= 35000 ~ "<=$35,000",
      HINCP_adj > 35000 & HINCP_adj <= 75000 ~ "$35,001-$75,000",
      HINCP_adj > 75000 & HINCP_adj <= 125000 ~ "$75,001-$125,000",
      HINCP_adj > 125000 & HINCP_adj <= 225000 ~ "$125,001-$225,000",
      HINCP_adj > 225000 ~ ">$225,000",
      .default = "Check"
    )
  ) |> 
  group_by(income.1) |> 
  summarise(
    hhds = sum(WGTP)
  ) |> 
  ungroup() |> 
  mutate(
    prop_hhds = round((hhds/sum(hhds))*100, 1)
  )

print(sum(income.1$hhds))

# Census Income Groupings Type 1
income.2 <- pums_cleaned |> 
  mutate(
    income.2 = case_when(
      HINCP_adj < 20000 ~ "<$20,000",
      HINCP_adj < 40000 & HINCP_adj >= 20000 ~ "$20,000-$39,999",
      HINCP_adj < 60000 & HINCP_adj >= 40000 ~ "$40,000-$59,999",
      HINCP_adj < 75000 & HINCP_adj >= 60000 ~ "$60,000-$74,999",
      HINCP_adj < 100000 & HINCP_adj >= 75000 ~ "$75,000-$99,999",
      HINCP_adj >= 100000 ~ ">=$100,000",
      .default = "Check"
    )
  ) |> 
  group_by(income.2) |> 
  summarise(
    hhds = sum(WGTP)
  ) |> 
  ungroup() |> 
  mutate(
    prop_hhds = round((hhds/sum(hhds))*100, 1)
  )

# Census Income Groupings Type 2
income.3 <- pums_cleaned |>
  mutate(
    income.3 = case_when(
      HINCP_adj < 15000 ~ "<$15,000",
      HINCP_adj < 35000 & HINCP_adj >= 15000 ~ "$15,000-$34,999",
      HINCP_adj < 75000 & HINCP_adj >= 35000 ~ "$35,000-$74,999",
      HINCP_adj < 150000 & HINCP_adj >= 75000 ~ "$75,000-$149,999",
      HINCP_adj >= 150000 ~ ">=$150,000",
      .default = "Check"
    )
  ) |> 
  group_by(income.3) |> 
  summarise(
    hhds = sum(WGTP)
  ) |> 
  ungroup() |> 
  mutate(
    prop_hhds = round((hhds/sum(hhds))*100, 1)
  )

# Census Income Groupings Type 3
income.4 <- pums_cleaned |> 
  mutate(
    income.4 = case_when(
      HINCP_adj < 10000 ~ "<$10,000",
      HINCP_adj < 15000 & HINCP_adj >= 10000 ~ "$10,000-$14,999",
      HINCP_adj < 20000 & HINCP_adj >= 15000 ~ "$15,000-$19,999",
      HINCP_adj < 25000 & HINCP_adj >= 20000 ~ "$20,000-$24,999",
      HINCP_adj < 30000 & HINCP_adj >= 25000 ~ "$25,000-$29,999",
      HINCP_adj < 35000 & HINCP_adj >= 30000 ~ "$30,000-$34,999",
      HINCP_adj < 40000 & HINCP_adj >= 35000 ~ "$35,000-$39,999",
      HINCP_adj < 45000 & HINCP_adj >= 40000 ~ "$40,000-$44,999",
      HINCP_adj < 50000 & HINCP_adj >= 45000 ~ "$45,000-$49,999",
      HINCP_adj < 60000 & HINCP_adj >= 50000 ~ "$50,000-$59,999",
      HINCP_adj < 75000 & HINCP_adj >= 60000 ~ "$60,000-$74,999",
      HINCP_adj < 100000 & HINCP_adj >= 75000 ~ "$75,000-$99,999",
      HINCP_adj < 125000 & HINCP_adj >= 100000 ~ "$100,000-$124,999",
      HINCP_adj < 150000 & HINCP_adj >= 125000 ~ "$125,000-$149,999",
      HINCP_adj < 200000 & HINCP_adj >= 150000 ~ "$150,000-$199,999",
      HINCP_adj >= 200000 ~ ">=$200,000",
      .default = "Check"
    )
  ) |> 
  group_by(income.4) |> 
  summarise(
    hhds = sum(WGTP)
  ) |> 
  ungroup() |> 
  mutate(
    prop_hhds = round((hhds/sum(hhds))*100, 1)
  )

# Brandon Thinks Its Important to know more about High Income Households 1\
income.5 <- pums_cleaned |> 
  mutate(
    income.5 = case_when(
      HINCP_adj < 25000 ~ "<$25,000",
      HINCP_adj < 50000 & HINCP_adj >= 25000 ~ "$25,000-$49,999",
      HINCP_adj < 75000 & HINCP_adj >= 50000 ~ "$50,000-$74,999",
      HINCP_adj < 100000 & HINCP_adj >= 75000 ~ "$75,000-$99,999",
      HINCP_adj < 125000 & HINCP_adj >= 100000 ~ "$100,000-$124,999",
      HINCP_adj < 150000 & HINCP_adj >= 125000 ~ "$125,000-$149,999",
      HINCP_adj < 175000 & HINCP_adj >= 150000 ~ "$150,000-$174,999",
      HINCP_adj < 200000 & HINCP_adj >= 175000 ~ "$175,000-$199,999",
      HINCP_adj < 225000 & HINCP_adj >= 200000 ~ "$200,000-$224,999",
      HINCP_adj < 250000 & HINCP_adj >= 225000 ~ "$225,000-$249,999",
      HINCP_adj < 275000 & HINCP_adj >= 250000 ~ "$250,000-$274,999",
      HINCP_adj < 300000 & HINCP_adj >= 275000 ~ "$275,000-$299,999",
      HINCP_adj < 400000 & HINCP_adj >= 300000 ~ "$300,000-$399,999",
      HINCP_adj < 500000 & HINCP_adj >= 400000 ~ "$400,000-$499,999",
      HINCP_adj >= 500000 ~ ">=$500,000",
      .default = "Check"
    )
  ) |> 
  group_by(income.5) |> 
  summarise(
    hhds = sum(WGTP)
  ) |> 
  ungroup() |> 
  mutate(
    prop_hhds = round((hhds/sum(hhds))*100, 1)
  )
  
```

# 4.0  Older Household Analysis
```{r}
```

# 5.0 Household Size Analysis
```{r}
```
# 6.0 Overcrowding Analysis
```{r}
```